# Generated by Django 4.2.5 on 2025-08-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Microsoft Integration',
                'verbose_name_plural': 'Microsoft Integrations',
                'db_table': 'uv_microsoft_integration',
            },
        ),
        migrations.CreateModel(
            name='Recaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteKey', models.CharField(blank=True, max_length=255, null=True)),
                ('secretKey', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'reCAPTCHA Setting',
                'verbose_name_plural': 'reCAPTCHA Settings',
                'db_table': 'uv_recaptcha',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191, unique=True)),
                ('logo', models.CharField(blank=True, max_length=191, null=True)),
                ('themeColor', models.CharField(max_length=191)),
                ('favicon', models.CharField(blank=True, max_length=191, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=191, null=True)),
                ('timeformat', models.CharField(blank=True, max_length=191, null=True)),
                ('businessHour', models.JSONField(blank=True, null=True)),
                ('businessHourStatus', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'db_table': 'uv_website',
            },
        ),
        migrations.CreateModel(
            name='SavedFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('filtering', models.JSONField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=190, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userinstance')),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'db_table': 'uv_saved_filters',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('subject', models.CharField(max_length=191)),
                ('message', models.TextField()),
                ('templateType', models.CharField(blank=True, max_length=255, null=True)),
                ('isPredefined', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userinstance')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'uv_email_templates',
            },
        ),
    ]
