# Generated by Django 4.2.5 on 2025-09-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0004_remove_userinstance_profileimagepath_and_more"),
        ("ticket", "0005_preparedresponse_groups_preparedresponse_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("viewed", models.IntegerField(default=0)),
                ("stared", models.IntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "uv_article",
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visibility", models.CharField(default="public", max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "solution_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="folder_images/"
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "db_table": "uv_solutions",
            },
        ),
        migrations.CreateModel(
            name="SolutionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "sorting",
                    models.CharField(
                        choices=[
                            ("ascending", "Ascending"),
                            ("descending", "Descending"),
                        ],
                        default="ascending",
                        max_length=20,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Solution Category",
                "verbose_name_plural": "Solution Categories",
                "db_table": "uv_solution_category",
            },
        ),
        migrations.CreateModel(
            name="RelatedArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "related_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="knowledgebase.article",
                    ),
                ),
            ],
            options={
                "db_table": "uv_related_articles",
                "unique_together": {("article", "related_article")},
            },
        ),
        migrations.CreateModel(
            name="MarketingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketing_module_images/"
                    ),
                ),
                (
                    "border_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link_url", models.URLField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.supportgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Module",
                "verbose_name_plural": "Marketing Modules",
                "db_table": "uv_marketing_module",
            },
        ),
        migrations.CreateModel(
            name="FolderCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledgebase.solutioncategory",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledgebase.folder",
                    ),
                ),
            ],
            options={
                "db_table": "uv_solution_category_mapping",
                "unique_together": {("folder", "category")},
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="categories",
            field=models.ManyToManyField(
                related_name="folders",
                through="knowledgebase.FolderCategory",
                to="knowledgebase.solutioncategory",
            ),
        ),
        migrations.CreateModel(
            name="ArticleViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.userinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article View Log",
                "verbose_name_plural": "Article View Logs",
                "db_table": "uv_article_view_log",
            },
        ),
        migrations.CreateModel(
            name="ArticleTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ticket.tag"
                    ),
                ),
            ],
            options={
                "db_table": "uv_article_tags",
                "unique_together": {("article", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ArticleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.userinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article History",
                "verbose_name_plural": "Article Histories",
                "db_table": "uv_article_history",
            },
        ),
        migrations.CreateModel(
            name="ArticleFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.userinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Feedback",
                "verbose_name_plural": "Article Feedback",
                "db_table": "uv_article_feedback",
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledgebase.article",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledgebase.solutioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "uv_article_category",
                "unique_together": {("article", "category")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                related_name="articles",
                through="knowledgebase.ArticleCategory",
                to="knowledgebase.solutioncategory",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(
                related_name="related_to",
                through="knowledgebase.RelatedArticles",
                to="knowledgebase.article",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="kb_articles",
                through="knowledgebase.ArticleTags",
                to="ticket.tag",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("promo_text", models.TextField(blank=True, null=True)),
                ("promo_tag", models.CharField(blank=True, max_length=255, null=True)),
                ("tag_color", models.CharField(blank=True, max_length=255, null=True)),
                ("link_text", models.CharField(blank=True, max_length=255, null=True)),
                ("link_url", models.URLField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.supportgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "db_table": "uv_announcement",
            },
        ),
    ]
