# Generated by Django 4.2.5 on 2025-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioncategory',
            name='folders',
            field=models.ManyToManyField(related_name='categories_through_category', through='knowledgebase.FolderCategory', to='knowledgebase.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='categories',
            field=models.ManyToManyField(related_name='folder_categories_reverse', through='knowledgebase.FolderCategory', to='knowledgebase.solutioncategory'),
        ),
    ]
