# Generated by Django 4.2.5 on 2025-09-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("code", models.CharField(max_length=191, unique=True)),
                ("logo", models.CharField(blank=True, max_length=191, null=True)),
                (
                    "theme_color",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                ("favicon", models.CharField(blank=True, max_length=191, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=191)),
                ("timeformat", models.CharField(default="24h", max_length=20)),
                ("business_hour", models.JSONField(blank=True, null=True)),
                ("business_hour_status", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "uv_website",
            },
        ),
        migrations.CreateModel(
            name="WebsiteKnowledgebase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="active", max_length=255)),
                (
                    "brand_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "page_background_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "header_background_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link_color", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "article_text_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ticket_create_option",
                    models.CharField(default="public", max_length=255),
                ),
                (
                    "site_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                (
                    "homepage_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("white_list", models.JSONField(blank=True, null=True)),
                ("black_list", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("broadcast_message", models.TextField(blank=True, null=True)),
                ("disable_customer_login", models.BooleanField(default=False)),
                ("script", models.TextField(blank=True, null=True)),
                ("custom_css", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("header_links", models.JSONField(blank=True, null=True)),
                ("footer_links", models.JSONField(blank=True, null=True)),
                (
                    "banner_background_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "link_hover_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("login_required_to_create", models.BooleanField(default=False)),
                ("remove_customer_login_button", models.BooleanField(default=False)),
                ("remove_branding_content", models.BooleanField(default=False)),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledgebase_config",
                        to="settings.website",
                    ),
                ),
            ],
            options={
                "db_table": "uv_website_knowledgebase",
            },
        ),
    ]
