# Generated by Django 4.2.5 on 2025-09-01 21:53

from django.db import migrations

def create_initial_website_data(apps, schema_editor):
    Website = apps.get_model('settings', 'Website')
    WebsiteKnowledgebase = apps.get_model('settings', 'WebsiteKnowledgebase')

    # Create Website records
    website1 = Website.objects.create(
        id=1,
        name='Support Center',
        code='help',
        theme_color='#7e91f0',
        is_active=True,
        timezone='UTC',
        timeformat='24h',
    )
    website2 = Website.objects.create(
        id=2,
        name='Helpdesk Knowledgebase',
        code='knowledgebase',
        theme_color='#7E91F0',
        is_active=True,
        timezone='UTC',
        timeformat='24h',
    )

    # Create WebsiteKnowledgebase record linked to website2 (id=2)
    WebsiteKnowledgebase.objects.create(
        website=website2,
        site_description='Hi! how can i help you.',
        status='active',
        ticket_create_option='public',
        is_active=True,
    )

class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_website_data),
    ]