# Generated by Django 4.2.5 on 2025-09-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial_website_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteknowledgebase',
            name='broadcast_from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteknowledgebase',
            name='broadcast_to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
