# Generated by Django 4.2.5 on 2025-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_websiteknowledgebase_broadcast_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteknowledgebase',
            name='broadcast_status',
            field=models.BooleanField(default=False),
        ),
    ]
