# Generated by Django 4.2.5 on 2025-09-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_populate_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="UvSwiftmailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=191, verbose_name="Friendly Name"),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("gmail", "Gmail"),
                            ("yahoo", "Yahoo"),
                        ],
                        max_length=10,
                        verbose_name="Transport Type",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=191, null=True, verbose_name="SMTP Host"
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="SMTP Port"
                    ),
                ),
                (
                    "encryption",
                    models.CharField(
                        choices=[("ssl", "SSL"), ("tls", "TLS"), ("null", "None")],
                        default="tls",
                        max_length=10,
                        verbose_name="Encryption Mode",
                    ),
                ),
                ("username", models.CharField(max_length=191, verbose_name="Username")),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                (
                    "sender_address",
                    models.CharField(max_length=191, verbose_name="Sender Address"),
                ),
            ],
            options={
                "verbose_name": "Swift Mailer Configuration",
                "verbose_name_plural": "Swift Mailer Configurations",
                "db_table": "uv_swiftmailer",
            },
        ),
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="UvMailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, verbose_name="Mailbox Name")),
                (
                    "email",
                    models.CharField(max_length=191, verbose_name="Email Address"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enable Mailbox"),
                ),
                (
                    "delete_after_fetch",
                    models.BooleanField(
                        default=False, verbose_name="Permanently delete from Inbox"
                    ),
                ),
                (
                    "imap_host",
                    models.CharField(
                        max_length=191, verbose_name="Incoming IMAP Server"
                    ),
                ),
                ("imap_port", models.IntegerField(verbose_name="Incoming IMAP Port")),
                (
                    "imap_encryption",
                    models.CharField(
                        choices=[("ssl", "SSL"), ("tls", "TLS"), ("null", "None")],
                        default="ssl",
                        max_length=10,
                        verbose_name="IMAP Encryption",
                    ),
                ),
                (
                    "imap_username",
                    models.CharField(max_length=191, verbose_name="IMAP Username"),
                ),
                (
                    "imap_password",
                    models.CharField(max_length=255, verbose_name="IMAP Password"),
                ),
                (
                    "outbound_transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailboxes",
                        to="settings.uvswiftmailer",
                        verbose_name="Outgoing Mail Transport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailbox Configuration",
                "verbose_name_plural": "Mailbox Configurations",
                "db_table": "uv_mailbox",
            },
        ),
        migrations.CreateModel(
            name="UvEmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_email",
                    models.CharField(max_length=191, verbose_name="System Email ID"),
                ),
                (
                    "system_sender_name",
                    models.CharField(max_length=191, verbose_name="System Sender Name"),
                ),
                (
                    "active_mailbox",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_settings",
                        to="settings.uvmailbox",
                        verbose_name="Active Mailbox for Incoming",
                    ),
                ),
                (
                    "active_swiftmailer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_settings",
                        to="settings.uvswiftmailer",
                        verbose_name="Default Swift Mailer for Outgoing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Setting",
                "verbose_name_plural": "Email Settings",
                "db_table": "uv_email_settings",
            },
        ),
    ]
