# Generated by Django 4.2.5 on 2025-08-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isActive", models.BooleanField(default=False)),
                ("userView", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Support Group",
                "verbose_name_plural": "Support Groups",
                "db_table": "uv_support_group",
            },
        ),
        migrations.CreateModel(
            name="SupportPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField()),
                ("privileges", models.JSONField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Support Privilege",
                "verbose_name_plural": "Support Privileges",
                "db_table": "uv_support_privilege",
            },
        ),
        migrations.CreateModel(
            name="SupportRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=191, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
            ],
            options={
                "verbose_name": "Support Role",
                "verbose_name_plural": "Support Roles",
                "db_table": "uv_support_role",
            },
        ),
        migrations.CreateModel(
            name="SupportTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isActive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Support Team",
                "verbose_name_plural": "Support Teams",
                "db_table": "uv_support_team",
            },
        ),
        migrations.CreateModel(
            name="SupportGroupsTeamsThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supportGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.supportgroup",
                    ),
                ),
                (
                    "supportTeam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.supportteam",
                    ),
                ),
            ],
            options={
                "db_table": "uv_support_groups_teams",
                "unique_together": {("supportGroup", "supportTeam")},
            },
        ),
        migrations.AddField(
            model_name="supportgroup",
            name="supportTeams",
            field=models.ManyToManyField(
                related_name="groups_with_team",
                through="authentication.SupportGroupsTeamsThrough",
                to="authentication.supportteam",
            ),
        ),
        migrations.CreateModel(
            name="LeadSupportTeamThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supportTeam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.supportteam",
                    ),
                ),
                (
                    "userInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userinstance",
                    ),
                ),
            ],
            options={
                "db_table": "uv_lead_support_teams",
                "unique_together": {("userInstance", "supportTeam")},
            },
        ),
        migrations.CreateModel(
            name="AdminSupportGroupThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supportGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.supportgroup",
                    ),
                ),
                (
                    "userInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userinstance",
                    ),
                ),
            ],
            options={
                "db_table": "uv_admin_support_groups",
                "unique_together": {("userInstance", "supportGroup")},
            },
        ),
        migrations.AddField(
            model_name="userinstance",
            name="admin_of_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="admins",
                through="authentication.AdminSupportGroupThrough",
                to="authentication.supportgroup",
            ),
        ),
        migrations.AddField(
            model_name="userinstance",
            name="lead_of_teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="leads",
                through="authentication.LeadSupportTeamThrough",
                to="authentication.supportteam",
            ),
        ),
        migrations.AddField(
            model_name="userinstance",
            name="supportGroups",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentication.supportgroup"
            ),
        ),
        migrations.AddField(
            model_name="userinstance",
            name="supportPrivileges",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_instances",
                to="authentication.supportprivilege",
            ),
        ),
        migrations.AddField(
            model_name="userinstance",
            name="supportRole",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_instances",
                to="authentication.supportrole",
            ),
        ),
        migrations.AddField(
            model_name="userinstance",
            name="supportTeams",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentication.supportteam"
            ),
        ),
    ]
