# Generated by Django A.B on YYYY-MM-DD HH:MM

from django.db import migrations
from ..constants import PRIVILEGE_CHOICES

def seed_data(apps, schema_editor):
    """Seeds the database with initial roles and a default privilege set."""
    SupportRole = apps.get_model('authentication', 'SupportRole')
    SupportPrivilege = apps.get_model('authentication', 'SupportPrivilege')

    # Seed SupportRoles
    roles = [
        'ROLE_SUPER_ADMIN',
        'ROLE_ADMIN',
        'ROLE_AGENT',
        'ROLE_CUSTOMER',
    ]
    for role_code in roles:
        SupportRole.objects.get_or_create(code=role_code, defaults={'description': f'{role_code.replace("_", " ").title()}'})

    # Seed a default SupportPrivilege set for agents
    all_privileges = list(PRIVILEGE_CHOICES['ticket'].keys()) + list(PRIVILEGE_CHOICES['advanced'].keys())
    
    SupportPrivilege.objects.get_or_create(
        name='Default Agent Privileges',
        defaults={
            'description': 'Default set of all privileges typically assigned to an agent.',
            'privileges': all_privileges
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_supportgroup_supportprivilege_supportrole_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]