# Generated by Django 4.2.5 on 2025-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_seed_initial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinstance",
            name="profileImagePath",
        ),
        migrations.AddField(
            model_name="userinstance",
            name="profileImage",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
