# Generated by Django 4.2.5 on 2025-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userinstance_profileimagepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verificationCode',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
