PREPARED_RESPONSE_ACTIONS = [
    ("uvdesk.agent.add_note", "Add note"),
    ("uvdesk.ticket.delete", "Delete Ticket"),
    ("uvdesk.ticket.mail_agent", "Mail to agent"),
    ("uvdesk.ticket.mail_customer", "Mail to customer"),
    ("uvdesk.ticket.mail_group", "Mail to group"),
    ("uvdesk.ticket.mail_last_collaborator", "Mail to last collaborator"),
    ("uvdesk.ticket.mail_team", "Mail to team"),
    ("uvdesk.ticket.mark_spam", "Mark spam"),
    ("uvdesk.ticket.assign_agent", "Assign to agent"),
    ("uvdesk.ticket.assign_group", "Assign to group"),
    ("uvdesk.ticket.update_priority", "Set Priority As"),
    ("uvdesk.ticket.update_status", "Set Status As"),
    ("uvdesk.ticket.update_tag", "Set Tag As"),
    ("uvdesk.ticket.assign_team", "Assign to team"),
    ("uvdesk.ticket.update_type", "Set Type As"),
]

EMAIL_TEMPLATES = [
    {
        "id": 1,
        "name": "User Forgot Password"
    },
    {
        "id": 2,
        "name": "Agent Reply To The Customer's ticket"
    },
    {
        "id": 3,
        "name": "Ticket generated by customer"
    },
    {
        "id": 4,
        "name": "Agent Account Created"
    },
    {
        "id": 5,
        "name": "Ticket Assign"
    },
    {
        "id": 6,
        "name": "Customer Reply To The Agent"
    },
    {
        "id": 7,
        "name": "Ticket generated success mail to customer"
    },
    {
        "id": 8,
        "name": "Customer Account Created"
    },
    {
        "id": 9,
        "name": "Collaborator added to ticket"
    },
    {
        "id": 10,
        "name": "Collaborator Reply To The Agent"
    },
    {
        "id": 11,
        "name": "Collaborator Reply To The Customer"
    }
]

PRIORITIES = ["low", "high", "medium", "urgent"]

STATUSES = ["open", "pending", "answered", "resolved", "close", "spam"]
