# Generated by Django 4.2.5 on 2025-08-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userinstance_profileimagepath_and_more'),
        ('ticket', '0003_auto_20250829_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreplies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userinstance'),
        ),
    ]
