# Generated by Django 4.2.5 on 2025-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_userinstance_profileimagepath_and_more"),
        ("ticket", "0004_alter_savedreplies_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparedresponse",
            name="groups",
            field=models.ManyToManyField(
                related_name="prepared_responses_groups",
                through="ticket.PreparedResponseSupportGroupsThrough",
                to="authentication.supportgroup",
            ),
        ),
        migrations.AddField(
            model_name="preparedresponse",
            name="teams",
            field=models.ManyToManyField(
                related_name="prepared_responses_teams",
                through="ticket.PreparedResponseSupportTeamsThrough",
                to="authentication.supportteam",
            ),
        ),
    ]
