# Generated by Django 4.2.5 on 2025-09-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_preparedresponse_groups_preparedresponse_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='isNew',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='referenceIds',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.TextField(),
        ),
    ]
