# Generated by Django 4.2.5 on 2025-09-01 23:36

from django.db import migrations

def populate_ticket_properties(apps, schema_editor):
    TicketStatus = apps.get_model('ticket', 'TicketStatus')
    TicketPriority = apps.get_model('ticket', 'TicketPriority')

    # Populate TicketStatus
    TicketStatus.objects.bulk_create([
        TicketStatus(code='open', description='Open', colorCode='#4CAF50', sortOrder=1),
        TicketStatus(code='pending', description='Pending', colorCode='#FFC107', sortOrder=2),
        TicketStatus(code='solved', description='Solved', colorCode='#2196F3', sortOrder=3),
        TicketStatus(code='spam', description='Spam', colorCode='#F44336', sortOrder=4),
    ])

    # Populate TicketPriority
    TicketPriority.objects.bulk_create([
        TicketPriority(code='low', description='Low', colorCode='#8BC34A'),
        TicketPriority(code='medium', description='Medium', colorCode='#FFEB3B'),
        TicketPriority(code='high', description='High', colorCode='#FF9800'),
        TicketPriority(code='urgent', description='Urgent', colorCode='#F44336'),
    ])

def reverse_ticket_properties(apps, schema_editor):
    TicketStatus = apps.get_model('ticket', 'TicketStatus')
    TicketPriority = apps.get_model('ticket', 'TicketPriority')

    TicketStatus.objects.filter(code__in=['open', 'pending', 'solved', 'spam']).delete()
    TicketPriority.objects.filter(code__in=['low', 'medium', 'high', 'urgent']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_isnew_remove_ticket_referenceids_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_ticket_properties, reverse_ticket_properties),
    ]