# Generated by Django 4.2.5 on 2025-09-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userinstance_profileimagepath_and_more'),
        ('ticket', '0007_populate_ticket_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactivity',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='supportlabel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_agent', to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='collaborators',
            field=models.ManyToManyField(related_name='tickets_as_collaborator', through='ticket.TicketCollaboratorsThrough', to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_customer', to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='ticketcollaboratorsthrough',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinstance'),
        ),
        migrations.AlterField(
            model_name='ticketrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinstance'),
        ),
    ]
