# Generated by Django 4.2.5 on 2025-09-03 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0008_alter_agentactivity_agent_alter_supportlabel_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
