# Generated by Django 4.2.5 on 2025-09-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0009_alter_thread_createdat_alter_ticket_createdat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="colorCode",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
